# Mullvad WireGuard tunnel — underlay for WARP.
#
# Traffic path:
#   LAN → CloudflareWARP (WARP/MASQUE) → wg-mullvad (WireGuard) → wan0 → Internet
#
# Result:
#   - Destination sees a Cloudflare/WARP IP
#   - Cloudflare sees a Mullvad exit IP (not your real IP)
#   - Your ISP sees WireGuard to Mullvad (not Cloudflare)
#
# Configuration values come from firewall.mullvad.* options, set in
# secrets-config.nix (generated by the setup wizard).
# The private key lives at /etc/secrets/mullvad/private-key (mode 0600).
{ config, lib, pkgs, ... }:

let
  cfg = config.firewall.mullvad;
in
{
  networking.wireguard.interfaces.wg-mullvad = {
    ips = [ cfg.address ];
    privateKeyFile = "/etc/secrets/mullvad/private-key";

    peers = [{
      publicKey = cfg.serverKey;
      endpoint = "${cfg.endpoint}:${toString cfg.port}";
      allowedIPs = [ "0.0.0.0/0" ];
      persistentKeepalive = 25;
    }];

    # We manage routes manually to avoid conflicts with WARP
    allowedIPsAsRoutes = false;

    postSetup = ''
      # Only set the endpoint route here — the broader routes are installed
      # by mullvad-routes.service after handshake is confirmed
      WAN_GW=""
      for i in $(seq 1 30); do
        WAN_GW=$(${pkgs.iproute2}/bin/ip route show dev wan0 default | ${pkgs.gawk}/bin/awk '{print $3}')
        [ -n "$WAN_GW" ] && break
        sleep 2
      done
      if [ -n "$WAN_GW" ]; then
        ${pkgs.iproute2}/bin/ip route replace ${cfg.endpoint}/32 via "$WAN_GW" dev wan0
      fi
    '';

    postShutdown = ''
      ${pkgs.iproute2}/bin/ip route del 0.0.0.0/1 dev wg-mullvad 2>/dev/null || true
      ${pkgs.iproute2}/bin/ip route del 128.0.0.0/1 dev wg-mullvad 2>/dev/null || true
      ${pkgs.iproute2}/bin/ip route del ${cfg.endpoint}/32 dev wan0 2>/dev/null || true
    '';
  };

  # Install default routes only after the WireGuard handshake succeeds.
  # Without this, a failed handshake blackholes all traffic.
  systemd.services.mullvad-routes = {
    description = "Install Mullvad default routes after handshake";
    after = [ "wireguard-wg-mullvad.service" ];
    requires = [ "wireguard-wg-mullvad.service" ];
    wantedBy = [ "multi-user.target" ];

    path = [ pkgs.wireguard-tools pkgs.iproute2 pkgs.gawk ];

    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };

    script = ''
      echo "Waiting for WireGuard handshake..."
      for i in $(seq 1 30); do
        HS=$(wg show wg-mullvad latest-handshakes 2>/dev/null | awk '{print $2}')
        if [ -n "$HS" ] && [ "$HS" != "0" ]; then
          echo "Handshake confirmed, installing routes"
          ip route replace 0.0.0.0/1 dev wg-mullvad
          ip route replace 128.0.0.0/1 dev wg-mullvad
          exit 0
        fi
        sleep 2
      done
      echo "ERROR: WireGuard handshake failed after 60s — routes NOT installed"
      exit 1
    '';
  };

  # WARP must start after Mullvad routes are active
  systemd.services.cloudflare-warp = {
    after = [ "mullvad-routes.service" ];
    wants = [ "mullvad-routes.service" ];
  };

  # Exclude the Mullvad endpoint from WARP's split tunnel so WARP's
  # firewall doesn't block WireGuard traffic.  This is persisted in
  # WARP's config (/var/lib/cloudflare-warp/) and survives reconnects.
  systemd.services.warp-exclude-mullvad = {
    description = "Exclude Mullvad endpoint from WARP split tunnel";
    after = [ "cloudflare-warp.service" ];
    wants = [ "cloudflare-warp.service" ];
    wantedBy = [ "multi-user.target" ];

    path = with pkgs; [ cloudflare-warp ];

    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };

    script = ''
      # Wait for WARP daemon to be ready
      for i in $(seq 1 30); do
        if warp-cli status &>/dev/null; then
          break
        fi
        sleep 1
      done
      # Add Mullvad endpoint to exclude list (idempotent — WARP ignores dupes)
      warp-cli tunnel ip add ${cfg.endpoint} || true
      echo "Mullvad endpoint ${cfg.endpoint} excluded from WARP split tunnel"
    '';
  };
}
