# Mullvad WireGuard tunnel — underlay for WARP.
#
# Traffic path:
#   LAN → CloudflareWARP (WARP/MASQUE) → wg-mullvad (WireGuard) → wan0 → Internet
#
# Result:
#   - Destination sees a Cloudflare/WARP IP
#   - Cloudflare sees a Mullvad exit IP (not your real IP)
#   - Your ISP sees WireGuard to Mullvad (not Cloudflare)
#
# Configuration values come from firewall.mullvad.* options, set in
# secrets-config.nix (generated by the setup wizard).
# The private key lives at /etc/secrets/mullvad/private-key (mode 0600).
{ config, lib, pkgs, ... }:

let
  cfg = config.firewall.mullvad;
in
{
  networking.wireguard.interfaces.wg-mullvad = {
    ips = [ cfg.address ];
    privateKeyFile = cfg.privateKeyFile;

    peers = [{
      publicKey = cfg.serverKey;
      endpoint = "${cfg.endpoint}:${toString cfg.port}";
      allowedIPs = [ "0.0.0.0/0" ];
      persistentKeepalive = 25;
    }];

    # We manage routes manually to avoid conflicts with WARP
    allowedIPsAsRoutes = false;

    postShutdown = ''
      ${pkgs.iproute2}/bin/ip route flush table 51820 2>/dev/null || true
      ${pkgs.iproute2}/bin/ip rule del not fwmark 0xca6c table 51820 2>/dev/null || true
      ${pkgs.iproute2}/bin/ip rule del table main suppress_prefixlength 0 2>/dev/null || true
      ${pkgs.iproute2}/bin/ip rule del fwmark 0x100 lookup 100 2>/dev/null || true
      ${pkgs.iproute2}/bin/ip route flush table 100 2>/dev/null || true
    '';
  };

  # Wait for handshake, then install fwmark-based routing.
  #
  # fwmark routing (same approach as wg-quick): WireGuard marks its
  # own transport packets → policy rule skips the tunnel table →
  # packets use the default route via wan0. No explicit endpoint
  # route needed, survives any gateway change.
  systemd.services.mullvad-routes = {
    description = "Install Mullvad fwmark routing after handshake";
    after = [ "wireguard-wg-mullvad.service" ];
    requires = [ "wireguard-wg-mullvad.service" ];
    wantedBy = [ "multi-user.target" ];

    path = [ pkgs.wireguard-tools pkgs.iproute2 pkgs.gawk ];

    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };

    script = ''
      echo "Waiting for WireGuard handshake..."
      for i in $(seq 1 60); do
        HS=$(wg show wg-mullvad latest-handshakes 2>/dev/null | awk '{print $2}')
        if [ -n "$HS" ] && [ "$HS" != "0" ]; then
          echo "Handshake confirmed, installing fwmark routing"

          wg set wg-mullvad fwmark 0xca6c
          ip route replace 0.0.0.0/1 dev wg-mullvad table 51820
          ip route replace 128.0.0.0/1 dev wg-mullvad table 51820
          ip rule add not fwmark 0xca6c table 51820 2>/dev/null || true
          ip rule add table main suppress_prefixlength 0 2>/dev/null || true

          # Split routing: non-web LAN traffic (fwmark 0x100) → Mullvad directly
          ip rule add fwmark 0x100 lookup 100 priority 100 2>/dev/null || true
          ip route replace default dev wg-mullvad table 100
          exit 0
        fi
        sleep 2
      done
      echo "ERROR: WireGuard handshake failed after 120s — routes NOT installed"
      exit 1
    '';
  };

  # WARP must start after Mullvad routes are active, and STOP when
  # Mullvad stops. BindsTo is the strict kill switch: if wg-mullvad
  # goes down, systemd stops WARP too, removing the CloudflareWARP
  # interface and ensuring no LAN traffic can escape unprotected.
  systemd.services.cloudflare-warp = {
    after = [ "mullvad-routes.service" ];
    requires = [ "mullvad-routes.service" ];
    bindsTo = [ "wireguard-wg-mullvad.service" ];
  };

}
