# Network interface configuration for a 4-port firewall appliance.
#
# Port layout:
#   - Port 1 (wan0):  upstream ISP/modem — DHCP
#   - Port 2 (lan1):  ┐
#   - Port 3 (lan2):  ├─ bridged as br-lan (10.0.1.1/24)
#   - Port 4 (lan3):  ┘
#
# The 3 LAN ports are bridged together so the box acts as a firewall + switch.
# The actual interface names (enp1s0, enp2s0, etc.) are mapped via systemd
# link units so the rest of the config uses stable names regardless of hardware.
#
# To find your MAC addresses, boot the NixOS installer and run: ip link
{ config, lib, pkgs, ... }:

let
  net = config.firewall.network;
in
{
  # ── Interface renaming ────────────────────────────────────────────────
  # MAC addresses come from firewall.network.* options, set in
  # secrets-config.nix (generated by the setup wizard).
  # To find your MAC addresses, boot the NixOS installer and run: ip link
  systemd.network.links = {
    "10-wan0" = {
      matchConfig.MACAddress = net.wan0Mac;
      linkConfig.Name = "wan0";
    };
    "10-lan1" = {
      matchConfig.MACAddress = net.lan1Mac;
      linkConfig.Name = "lan1";
    };
    "10-lan2" = {
      matchConfig.MACAddress = net.lan2Mac;
      linkConfig.Name = "lan2";
    };
    "10-lan3" = {
      matchConfig.MACAddress = net.lan3Mac;
      linkConfig.Name = "lan3";
    };
  };

  # ── Use systemd-networkd (not NetworkManager) ────────────────────────
  networking.useDHCP = false;
  networking.networkmanager.enable = lib.mkForce false;
  systemd.network.enable = true;

  # ── Bridge: combine 3 LAN ports into br-lan ─────────────────────────
  systemd.network.netdevs."10-br-lan" = {
    netdevConfig = {
      Name = "br-lan";
      Kind = "bridge";
    };
  };

  systemd.network.networks = {
    # WAN — DHCP from ISP
    "20-wan0" = {
      matchConfig.Name = "wan0";
      networkConfig = {
        DHCP = "ipv4";
      };
      dhcpV4Config = {
        UseDNS = false;
        UseRoutes = true;
        RouteMetric = 100;
      };
      linkConfig.RequiredForOnline = "no";
    };

    # LAN ports — enslaved to br-lan
    "20-lan1" = {
      matchConfig.Name = "lan1";
      networkConfig.Bridge = "br-lan";
      linkConfig.RequiredForOnline = "no";
    };
    "20-lan2" = {
      matchConfig.Name = "lan2";
      networkConfig.Bridge = "br-lan";
      linkConfig.RequiredForOnline = "no";
    };
    "20-lan3" = {
      matchConfig.Name = "lan3";
      networkConfig.Bridge = "br-lan";
      linkConfig.RequiredForOnline = "no";
    };

    # Bridge — this is the LAN gateway
    "20-br-lan" = {
      matchConfig.Name = "br-lan";
      networkConfig = {
        Address = "192.168.1.1/24";
        DHCPServer = false; # We use Kea instead for full control
        KeepConfiguration = "static";
      };
      linkConfig.RequiredForOnline = "routable";
    };
  };

  # iproute2 for general network management
  networking.iproute2.enable = true;
}
