# Firewall appliance options — populated by secrets-config.nix (generated by
# the setup wizard, never committed to git).
{ config, lib, ... }:

let
  inherit (lib) mkOption types;
in
{
  options.firewall = {
    user = {
      name = mkOption {
        type = types.str;
        default = "admin";
        description = "Username for the admin account.";
      };
      sshKeys = mkOption {
        type = types.listOf types.str;
        default = [];
        description = "SSH public keys for the admin account.";
      };
      hostName = mkOption {
        type = types.str;
        default = "nixos-firewall";
        description = "System hostname.";
      };
    };

    network = {
      wan0Mac = mkOption {
        type = types.str;
        default = "UNCONFIGURED";
        description = "MAC address for the WAN port.";
      };
      lan1Mac = mkOption {
        type = types.str;
        default = "UNCONFIGURED";
        description = "MAC address for LAN port 1.";
      };
      lan2Mac = mkOption {
        type = types.str;
        default = "UNCONFIGURED";
        description = "MAC address for LAN port 2.";
      };
      lan3Mac = mkOption {
        type = types.str;
        default = "UNCONFIGURED";
        description = "MAC address for LAN port 3.";
      };
    };

    mullvad = {
      endpoint = mkOption {
        type = types.str;
        default = "UNCONFIGURED";
        description = "Mullvad WireGuard server endpoint IP.";
      };
      port = mkOption {
        type = types.port;
        default = 51820;
        description = "Mullvad WireGuard server port.";
      };
      serverKey = mkOption {
        type = types.str;
        default = "UNCONFIGURED";
        description = "Mullvad WireGuard server public key.";
      };
      address = mkOption {
        type = types.str;
        default = "10.0.0.1/32";
        description = "Tunnel address assigned by Mullvad (CIDR).";
      };
    };
  };
}
