# Firewall appliance options — populated by secrets-config.nix (generated by
# the setup wizard, never committed to git).
{ config, lib, ... }:

let
  inherit (lib) mkOption types;
  cfg = config.firewall;
in
{
  options.firewall = {
    user = {
      name = mkOption {
        type = types.str;
        default = "admin";
        description = "Username for the admin account.";
      };
      sshKeys = mkOption {
        type = types.listOf types.str;
        default = [];
        description = "SSH public keys for the admin account.";
      };
      hostName = mkOption {
        type = types.str;
        default = "nixos-firewall";
        description = "System hostname.";
      };
    };

    network = {
      wan0Mac = mkOption {
        type = types.str;
        default = "UNCONFIGURED";
        description = "MAC address for the WAN port.";
      };
      lan1Mac = mkOption {
        type = types.str;
        default = "UNCONFIGURED";
        description = "MAC address for LAN port 1.";
      };
      lan2Mac = mkOption {
        type = types.str;
        default = "";
        description = "MAC address for LAN port 2 (optional).";
      };
      lan3Mac = mkOption {
        type = types.str;
        default = "";
        description = "MAC address for LAN port 3 (optional).";
      };
    };

    wanAllowedTCPPorts = mkOption {
      type = types.listOf types.port;
      default = [];
      description = "TCP ports to allow inbound on wan0.";
    };

    mullvad = {
      endpoint = mkOption {
        type = types.str;
        default = "UNCONFIGURED";
        description = "Mullvad WireGuard server endpoint IP.";
      };
      port = mkOption {
        type = types.port;
        default = 51820;
        description = "Mullvad WireGuard server port.";
      };
      serverKey = mkOption {
        type = types.str;
        default = "UNCONFIGURED";
        description = "Mullvad WireGuard server public key.";
      };
      address = mkOption {
        type = types.str;
        default = "10.0.0.1/32";
        description = "Tunnel address assigned by Mullvad (CIDR).";
      };
      privateKeyFile = mkOption {
        type = types.str;
        default = "/etc/secrets/mullvad/private-key";
        description = "Path to the WireGuard private key file. Overridden by sops.nix in production.";
      };
    };
  };

  config.assertions = [
    {
      assertion = cfg.network.wan0Mac != "UNCONFIGURED";
      message = "firewall.network.wan0Mac is not set. Create secrets-config.nix with your WAN port MAC address.";
    }
    {
      assertion = cfg.network.lan1Mac != "UNCONFIGURED";
      message = "firewall.network.lan1Mac is not set. Create secrets-config.nix with your LAN port 1 MAC address.";
    }
    {
      assertion = cfg.mullvad.endpoint != "UNCONFIGURED";
      message = "firewall.mullvad.endpoint is not set. Add your Mullvad server endpoint to secrets-config.nix.";
    }
    {
      assertion = cfg.mullvad.serverKey != "UNCONFIGURED";
      message = "firewall.mullvad.serverKey is not set. Add your Mullvad server public key to secrets-config.nix.";
    }
    {
      assertion = cfg.user.sshKeys != [];
      message = "firewall.user.sshKeys is empty. Add at least one SSH public key to secrets-config.nix or you will be locked out.";
    }
  ];
}
