# E2E firewall VM — runs the production stack inside QEMU.
#
# NIC layout (set by tests/e2e/run-e2e.sh QEMU launch flags):
#   eth0 = mgmt slirp     — SSH access from host (10.0.2.0/24, no default route)
#   eth1 = vlan1 socket   — renamed to wan0; talks to upstream VM
#   eth2 = vlan2 socket   — renamed to lan1; bridged into br-lan, talks to client VM
#
# The mgmt slirp on eth0 gives the host runner a path to drive the VM via SSH;
# it deliberately does NOT install a default route so that production traffic
# can only exit via wan0 (and therefore via the WARP/Mullvad tunnels).
#
# Mullvad credentials come from tests/e2e/.runtime/secrets.nix, which is
# generated by the runner script after sops-decrypting tests/e2e/secrets/mullvad.yaml.
{ config, lib, pkgs, modulesPath, ... }:

let
  # The runner exports E2E_MULLVAD_JSON as an absolute path to the
  # sops-decrypted secrets JSON. We read via getEnv + readFile so the file
  # doesn't have to be tracked by git for the flake to find it. Requires
  # nix build --impure (the runner sets that flag).
  secretsPath = builtins.getEnv "E2E_MULLVAD_JSON";
  secrets =
    if secretsPath != "" && builtins.pathExists secretsPath
    then (builtins.fromJSON (builtins.readFile secretsPath))
    else throw ''
      Missing E2E_MULLVAD_JSON or its target.
      Run tests/e2e/run-e2e.sh — it sops-decrypts your Mullvad creds and
      exports E2E_MULLVAD_JSON before invoking nix build --impure.
    '';

  # Same pattern for the ephemeral SSH pubkey the runner uses to drive the VM.
  pubkeyPath = builtins.getEnv "E2E_SSH_PUBKEY_FILE";
  runnerPubkey =
    if pubkeyPath != "" && builtins.pathExists pubkeyPath
    then builtins.readFile pubkeyPath
    else throw ''
      Missing E2E_SSH_PUBKEY_FILE or its target.
      run-e2e.sh generates a runner keypair and exports this var.
    '';
in
{
  imports = [
    ../../configuration.nix
    ../../modules/options.nix
    ../../modules/network.nix
    ../../modules/firewall.nix
    ../../modules/dhcp-dns.nix
    ../../modules/warp.nix
    ../../modules/mullvad.nix
  ];

  # ── VM identity & access ───────────────────────────────────────────
  networking.hostName = lib.mkForce "e2e-firewall";
  services.getty.autologinUser = "root";

  # SSH listens on every iface for the mgmt slirp (production binds 192.168.1.1)
  services.openssh.listenAddresses = lib.mkForce [ ];
  services.openssh.settings.PermitRootLogin = lib.mkForce "yes";
  users.users.root.openssh.authorizedKeys.keys = [ runnerPubkey ];


  # ── VM overrides for things configuration.nix can't satisfy in QEMU ─
  boot.loader.systemd-boot.enable = lib.mkForce false;
  boot.loader.efi.canTouchEfiVariables = lib.mkForce false;
  systemd.watchdog = lib.mkForce { };

  # ── Mullvad credentials from sops-decrypted secrets ────────────────
  firewall.mullvad = {
    endpoint  = secrets.mullvad.endpoint;
    port      = secrets.mullvad.port;
    serverKey = secrets.mullvad.serverKey;
    address   = secrets.mullvad.address;
  };

  # mullvad.nix reads its private key from disk; place the decrypted key
  # at the path the production module expects.
  systemd.tmpfiles.rules = [
    "d /etc/secrets 0700 root root - -"
    "d /etc/secrets/mullvad 0700 root root - -"
  ];
  environment.etc."secrets/mullvad/private-key" = {
    text = secrets.mullvad.privateKey;
    mode = "0600";
  };

  # ── Interface naming: use the production MAC-based link rules ──────
  # Instead of overriding .link files with OriginalName matching (which
  # fails under net.ifnames=0 in QEMU), set the production MAC options
  # to the stable QEMU MACs assigned in run-e2e.sh. This lets the
  # standard network.nix MAC-based .link rules rename the interfaces.
  #
  # TODO: options.nix hardcodes exactly 4 ports (wan0 + 3 LAN). Make
  # the port list dynamic so systems with arbitrary port counts don't
  # need dummy MACs for nonexistent interfaces.
  firewall.network.wan0Mac = "52:54:00:11:00:01";
  firewall.network.lan1Mac = "52:54:00:11:00:02";
  firewall.network.lan2Mac = "52:54:00:11:00:03";
  firewall.network.lan3Mac = "52:54:00:11:00:04";

  # eth0 = mgmt slirp. DHCP for the IP, but no default route — production
  # routing must own that.
  systemd.network.networks."05-mgmt" = {
    matchConfig.Name = "eth0";
    networkConfig.DHCP = "ipv4";
    dhcpV4Config = {
      UseRoutes = false;
      UseDNS = false;
      UseHostname = false;
    };
    linkConfig.RequiredForOnline = "no";
  };

  # wan0: static IP on the "WAN segment" with default route via upstream VM.
  # The mullvad endpoint route stays on wan0 (set by mullvad.nix postSetup);
  # everything else gets replaced by wg-mullvad after handshake.
  systemd.network.networks."20-wan0" = lib.mkForce {
    matchConfig.Name = "wan0";
    networkConfig = {
      Address = "10.99.0.2/24";
      Gateway = "10.99.0.1";
      DNS = "1.1.1.1";
    };
    linkConfig.RequiredForOnline = "routable";
  };

  # ── Convenience packages for the test driver ───────────────────────
  environment.systemPackages = with pkgs; [
    tcpdump
    wireguard-tools
    iproute2
    iputils
    curl
    dnsutils
    jq
  ];

  # ── Boot/serial/QEMU knobs ─────────────────────────────────────────
  boot.kernelParams = [ "console=ttyS0,115200" ];

  virtualisation = {
    memorySize = 2048;
    cores = 2;
    diskSize = 6144;
    graphics = false;
    # No host port-forward for SSH — the test driver reaches the firewall via
    # the client VM as a jump host (client is on br-lan which nftables allows).
  };
}
